	modLoader="javafml"
	loaderVersion="[36,)"
	license="MIT"
	
[[mods]]
	modId="netherpearls"
	version="1.0"
	displayName="Netherpearls"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/nether-pearls"
	issueTrackerURL="https://github.com/kregerl/NetherPearls/issues"
	logoFile="netherPearlLogo.png"
	credits=""
	authors="AreUThreateningMe"
	description='''
Nether pearls work the same way as ender pearls, except the player is placed at their coordinated in the nether / overworld depending on the players current dimension.
'''

[[dependencies.netherpearls]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.netherpearls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="AFTER"
    side="BOTH"
